sacred_config: staging
train_experiment_id: 147
use_sandbox_api: true

job:
  node_group: c2-standard-4

  controller:
    num_cpus: 0.8
    memory: 3000Mi

  model_server:
    num_cpus: 2.6
    memory: 10000Mi

# Add in dummy values for secrets so linting passes
SANDBOX_COINBASE_API_KEY_B64SECRET: test
SANDBOX_COINBASE_API_KEY_NAME: test
SANDBOX_COINBASE_API_KEY_PASSPHRASE: test

gitlab-token-secret:
  CI_TOKEN: test

mongo-db-secret:
  mongodb_url: test

gitlab-registry-secret:
  registry:
    username: test
    password: test
