---
{{ if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-coinbase-train
  labels:
    app: coinbase-train
spec:
  template:
    spec:

      {{ if gt .Values.job.num_gpus 0.0}}
      tolerations:
      - key: "gpu"
        operator: "Exists"
        effect: "NoSchedule"
      {{ end }}

      imagePullSecrets:
      - name: {{ .Release.Name }}-registry-credentials

      restartPolicy: OnFailure
      
      containers:
      - name: coinbase-train

        command: 
          - 'python3'
          - 'coinbase_train/train.py'
          - 'with'
          - 'staging'

        env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sacred-mongodb
                key: mongodb-root-password

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password

        {{ if gt .Values.job.num_gpus 0.0}}
        image: "registry.gitlab.com/moonraker/coinbase_train/gpu:{{ .Chart.Version }}"
        {{ else }}
        image: "registry.gitlab.com/moonraker/coinbase_train/cpu:{{ .Chart.Version }}"
        {{ end }}

        resources:
          limits:
            cpu: {{ .Values.job.num_cpus }}
            nvidia.com/gpu: {{ .Values.job.num_gpus }}


{{ end }}
