---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: {{ .Values.jupyter.num_replicas }}
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:

      imagePullSecrets:
      - name: coinbase-train-regcred
      
      containers:
      
      - name: jupyter

        {{ if gt .Values.jupyter.num_gpus 0.0}}
        image: {{ .Values.jupyter.image_base }}/gpu:{{ .Values.jupyter.image_tag }}
        {{ else }}
        image: {{ .Values.jupyter.image_base }}/cpu:{{ .Values.jupyter.image_tag }}
        {{ end }}
      
        command: ["jupyter"]
        args: ["lab", "--ip=0.0.0.0", "--allow-root"]

        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username

        ports:
        - containerPort: 8888
          name: jupyter-port

        volumeMounts:
        - name: jupyter
          mountPath: /mnt

        resources:
          requests:
            cpu: {{ .Values.jupyter.num_cpus }}
            nvidia.com/gpu: {{ .Values.jupyter.num_gpus }}
          limits:
            cpu: {{ .Values.jupyter.num_cpus }}
            nvidia.com/gpu: {{ .Values.jupyter.num_gpus }}

  volumeClaimTemplates:
  - metadata:
      name: jupyter
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.jupyter.storage_request }}