---
{{$release_name := .Release.Name | trunc 14}}
{{if gt .Values.notebook.num_cpus 0.0}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$release_name}}-notebook
  labels:
    app: train
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      pod-selector: {{$release_name}}-notebook-train
  template:
    metadata:
      labels:
        pod-selector: {{$release_name}}-notebook-train
    spec:

      {{- if .Values.notebook.node_group}}
      nodeSelector:
        node-group: {{.Values.notebook.node_group}}
      {{- end}}

      {{- if .Values.notebook.node_group}}
      tolerations:
      - key: node-group
        operator: "Equal"
        effect: "NoSchedule"
        value: {{.Values.notebook.node_group}}
      {{- end}}

      imagePullSecrets:
      - name: {{.Release.Name}}-registry-credentials

      containers:

      - name: jupyter

        command: ["/bin/bash"]
        args: ["-c", "connect_to_ray_cluster && start_jupyter_lab"]

        workingDir: /

        env:
          - name: ENVIRONMENT
            value: {{.Values.ENVIRONMENT}}

          - name: MONGO_DB_URL
            valueFrom:
              secretKeyRef:
                name: {{$release_name}}-mongodb-credentials
                key: mongodb-url

          - name: NUM_GPUS
            value: {{.Values.notebook.num_gpus | quote}}

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password

          {{- if .Values.ray.deploy_ray_cluster}}
          - name: RAY_REDIS_ADDRESS
            value: {{.Release.Name}}-ray-head:6379
          {{- end}}

        imagePullPolicy: Always
        {{if gt .Values.notebook.num_gpus 0.0}}
        image: "registry.gitlab.com/moonraker/coinbase_train/gpu:{{ .Chart.Version }}"
        {{else}}
        image: "registry.gitlab.com/moonraker/coinbase_train/cpu:{{ .Chart.Version }}"
        {{end}}

        ports:
        - containerPort: 8888
          name: notebook-port1
        - containerPort: 8889
          name: notebook-port2
        {{- if .Values.ray.deploy_ray_cluster}}
        - containerPort: 6379
          name: redis
        - containerPort: 12345
          name: plasma
        {{- end}}

        resources:
          limits:
            cpu: {{.Values.notebook.num_cpus}}
            nvidia.com/gpu: {{.Values.notebook.num_gpus}}

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm

          - mountPath: /secrets
            name: service-account-json
            readOnly: true


      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

      - name: service-account-json
        secret:
          secretName: {{$release_name}}-service-account-json
{{end}}
