---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    name: jupyter-port
  selector:
    app: jupyter