---
{{$release_name := .Release.Name | trunc 14}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$release_name}}-mongodb-credentials
  app: train
type: Opaque
data:
  mongodb-url: {{.Values.mongodb_url | b64enc}}
