version: '3'
services:

  train:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    image: 'registry.gitlab.com/moonraker/gdax_train/gdax_train:latest'
    volumes:
      - /var/log/sacred_tensorboard:/var/log/sacred_tensorboard
      - /var/moonraker_models:/var/moonraker_models
    entrypoint: python3 train.py
    env_file:
     - secrets.env
    networks:
      - infrastructure_moonraker

networks:
  infrastructure_moonraker:
    external: true
