version: '3'
services:

  train:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - /var/log/sacred_tensorboard:/var/log/sacred_tensorboard
      - /var/moonraker_models:/var/moonraker_models
    env_file:
     - secrets.env
    networks:
      - infrastructure_moonraker

networks:
  infrastructure_moonraker:
    external: true
