
# This docker-compose file is intended for running tests in Gitlab-CI
# If you want to run tests locally please see the Makefile
version: '3'
services:
  coinbase_ml_tests:
    command: make build-python-protos test
    build:
      args:
          TEST_MODE: "true"
      context: .
      dockerfile: dockerfiles/Dockerfile.cpu
    network_mode: host
    volumes:
      - /tmp/coinbase_ml/docker-entrypoint-initdb.d:/tmp/coinbase_ml/docker-entrypoint-initdb.d
      - /var/run/docker.sock:/var/run/docker.sock:ro