version: '3'
services:

  train:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
     - secrets.env
    networks:
      - infrastructure_moonraker

networks:
  infrastructure_moonraker:
    external: true
