environment: staging

node_group: c2-standard-4

resources:
  limits:
    memory: 13000Mi
    cpu: 3.6
  requests:
    memory: 13000Mi
    cpu: 3.5

gcp_service_account_secret:
  mount_path: /var/moonraker/coinbaseml

# mock values for secrets so linting doesn't fail
service_account_json: test

gitlab-registry-secret:
  registry:
    username: test
    password: test