job:
  resources:
    limits:
      memory: 13000Mi
      cpu: 3.6
      nvidia.com/gpu: 0
    requests:
      memory: 13000Mi
      cpu: 3.6
      nvidia.com/gpu: 0
  node_group: c2-standard-4
  sacred_config: bollinger_on_book_volume_staging

ray:
  gcp_service_account_secret:
    enabled: false
    mount_path: /var/moonraker/coinbaseml

  gitlab-registry-secret:
    enabled: false
    registry:
      username: test
      password: test

  deploy_ray_cluster: true

  head_deployment:
    memory: 13000Mi
    num_cpus: 3.6
    num_gpus: 0
    node_group: c2-standard-4

  worker_deployments:
    cpu-workers:
      memory_per_replica: 13000Mi
      num_cpus_per_replica: 3.6
      num_gpus_per_replica: 0
      num_replicas: 4
      node_group: c2-standard-4

# Add in dummy values for secrets so linting passes
gitlab-token-secret:
  CI_TOKEN: test

mongo-db-secret:
  mongodb_url: test

gitlab-registry-secret:
  registry:
    username: test
    password: test

