"""Constants for supervised module
"""

from typing import List

import pandas as pd


class Columns:
    """Columns of Pandas DataFrames used in the module
    """

    LABEL = "label"
    UPPER_BARRIER = "upper_barrier"
    LOWER_BARRIER = "lower_barrier"


class FeatureNames:
    """Names of features generated by module
    """

    ORDER_BOOK = "orderBook"


class PortfolioParameters:
    """Parameters passed into for a portfolio before evaluating
    """

    BARRIER_TIME_STEPS = "barrier_time_steps"
    FEE_FRACTION = "fee_fraction"
    INITIAL_QUOTE_FUNDS = "initial_quote_funds"
    PERFORMANCE_METRIC = "performance_metric"


class Labels:
    """Labels assigned by the triple barrier method
    """

    NEGATIVE = -1.0
    NEUTRAL = 0.0
    POSITIVE = 1.0

    @classmethod
    def as_list(cls) -> List[float]:
        return [cls.NEGATIVE, cls.NEUTRAL, cls.POSITIVE]


class PerformanceMetrics:
    """Metrics against which a portfolio can be optimized
    """

    SHARPE_RATIO = "sharpe_ratio"


MAX_TIMESTAMP = pd.Timestamp("2262-04-11 23:47:16.854775807")
