import pandas as pd
import vectorbt as vbt

from coinbase_ml.supervised.constants import Columns, Labels
from coinbase_ml.supervised.label import calc_triple_barrier_labels_and_barriers


def create_portfolio_with_triple_barrier_positions(
    prices: pd.Series,
    barrier_time_steps: int,
    initial_quote_funds: float,
    fee_fraction: float,
) -> vbt.Portfolio:
    """Creates a portfolio from with positions generated by the triple barrier method.
    """
    labels = calc_triple_barrier_labels_and_barriers(prices, barrier_time_steps)[
        Columns.LABEL
    ]
    entries = labels == Labels.POSITIVE
    exits = labels == Labels.NEGATIVE

    return vbt.Portfolio.from_signals(
        prices, entries, exits, init_cash=initial_quote_funds, fees=fee_fraction
    )
