---
{{$release_name := .Release.Name | trunc 14}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$release_name}}-gitlab-ci-token
  app: train
type: Opaque
data:
  CI_TOKEN: {{.Values.CI_TOKEN | b64enc}}
