---
{{$release_name := .Release.Name | trunc 14}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$release_name}}-service-account-json
  app: train
type: Opaque
data:
  service-account.json: {{.Values.service_account_json}}
