# syntax=docker/dockerfile:1.0.0-experimental
FROM registry.gitlab.com/moonraker/base_images/python_gpu:0.1.0-b48168abce54ba7faf1b0b5ddbb745078f916e34

ENV PYTHONPATH=/app

RUN mkdir /var/log/sacred_tensorboard /var/moonraker_models

ADD ./ /app

WORKDIR /app

RUN --mount=type=secret,id=gitlab_credentials.ini \
	python3 setup.py install --gpu
