# syntax=docker/dockerfile:1.0.0-experimental
FROM python:3.6

ENV PYTHONPATH=/app

ADD ./ /app

WORKDIR /app

RUN --mount=type=secret,id=gitlab_credentials.ini \
    apt-get update && \
	apt-get install -y git && \
	make install && \
	chmod -R o+rx /usr/local/lib/python3.6/site-packages/ray*
