# syntax=docker/dockerfile:1.0.0-experimental
FROM registry.gitlab.com/moonraker/base_images/coinbase_train_cpu:0.1.0-3ac9ee0bdf065e93a4a7fb5f6f157ee028512e79

ENV PYTHONPATH=/app

ADD ./ /app

WORKDIR /app

RUN --mount=type=secret,id=gitlab_credentials.ini \
	make install && \
	chmod -R o+rx /usr/local/lib/python3.7/dist-packages/ray*
