ARG BUILDER_BASE_IMAGE_VERSION=0.1.0-ace523e3c28c523eba2f45e89a1d3265c2e9b872

ARG RUNTIME_BASE_IMAGE_VERSION=0.1.0-d464dddbf3db8bf24408070f8264350e882aca12

FROM registry.gitlab.com/moonraker/base_images/coinbase_train_sbt:${BUILDER_BASE_IMAGE_VERSION} AS sbt-builder

ARG PROJECT=coinbaseml

ADD ./ /app

WORKDIR /app

RUN make build-scala project=$PROJECT

FROM registry.gitlab.com/moonraker/base_images/coinbase_train_cpu:${RUNTIME_BASE_IMAGE_VERSION}

ENV LANG=C.UTF-8 \
	LD_BIND_NOW=1 \
	PYTHONUNBUFFERED=1 \
	PYTHONPATH=/app \
	RAY_USE_MULTIPROCESSING_CPU_COUNT=1 \
	PATH="/usr/lib/graalvm/graalvm-ce-java11-20.2.0/bin/:${PATH}"

ADD ./ /app

WORKDIR /app

COPY --from=sbt-builder /tmp/moonraker/coinbaseml/coinbaseml.jar /tmp/moonraker/coinbaseml/coinbaseml.jar

RUN make install-gpu && \
	make build-python-protos && \
	chmod -R o+rx /usr/local/lib/python3.7/dist-packages/ray*
