# syntax=docker/dockerfile:1.0.0-experimental
FROM registry.gitlab.com/moonraker/base_images/coinbase_train_gpu:0.1.0-ac7f3387de593716b2478b5b8efb5775300283da

ENV PYTHONPATH=/app

RUN mkdir /var/log/sacred_tensorboard /var/moonraker_models

ADD ./ /app

WORKDIR /app

RUN --mount=type=secret,id=gitlab_credentials.ini \
	python3 setup.py install --gpu
