job:
  resources:
    limits:
      memory: 22000Mi
      cpu: 3.6
      nvidia.com/gpu: 1
    requests:
      memory: 22000Mi
      cpu: 3.5
      nvidia.com/gpu: 1
  node_group: n1-highmem-4-nvidia-tesla-p100
  sacred_config: staging

notebook:
  resources:
    limits:
      memory: 22000Mi
      cpu: 0.0
      nvidia.com/gpu: 1
    requests:
      memory: 22000Mi
      cpu: 0.0
      nvidia.com/gpu: 1
  node_group: n1-highmem-4-nvidia-tesla-p100

ray:
  gcp_service_account_secret:
    enabled: false
    mount_path: /var/moonraker/coinbaseml

  gitlab-registry-secret:
    enabled: false
    registry:
      username: test
      password: test

  deploy_ray_cluster: true

  head_deployment:
    memory: 13000Mi
    num_cpus: 3.6
    num_gpus: 0
    node_group: c2-standard-4

  worker_deployments:
    cpu-workers:
      memory_per_replica: 13000Mi
      num_cpus_per_replica: 3.6
      num_gpus_per_replica: 0
      num_replicas: 0
      node_group: c2-standard-4

# Add in dummy values for secrets so linting passes
CI_TOKEN: test
mongodb_url: test

mongodb-secret:
  mongodb_url: test

gitlab-registry-secret:
  registry:
    username: test
    password: test

