---
{{$release_name := .Release.Name | trunc 14}}
apiVersion: v1
kind: Service
metadata:
  name: {{$release_name}}-trend-following
  labels:
    app: train
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: ray-webui
  selector:
    pod-selector: {{$release_name}}-trend-following
